name: Build

on:
  pull_request:
<<<<<<< HEAD
    branches: [main, feat/*, dev]
    types: [opened, ready_for_review]
  push:
    branches: [dev]
=======
    branches: [main, feat/*]
    types: [opened, ready_for_review]
  push:
    branches: [main, dev, feat/*]
>>>>>>> 346a896 (test)
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Set up Go
        uses: actions/setup-go@v3
        with:
          go-version: 1.23.6
<<<<<<< HEAD
=======

>>>>>>> 346a896 (test)
      - name: Build
        run: go build -v ./...
